In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
import re

# Data Importing

Grab a random one from the file list

In [170]:
filename = "washei50433.BQSR.recaled.bam"

In [171]:
def get_file(bam_name):
    '''
    given a bam name, read the variantsAnnotate.txt inside the output of Coassin pipeline
    Args:
        bam name: str, the name of the original bam file
    Return:
        pandas.DataFrame instance, the variantsAnnotate.txt file read
    '''
    return pd.read_csv(f'data/{bam_name}/variantsAnnotate/variantsAnnotate.txt', delimiter = "\t")

In [184]:
db = get_file(filename)
print(db.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 364 entries, 0 to 363
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   SampleID        364 non-null    object
 1   Pos             364 non-null    int64
 2   Ref             364 non-null    object
 3   Variant         364 non-null    object
 4   Major/Minor     364 non-null    object
 5   Variant-Level   364 non-null    float64
 6   Coverage-FWD    364 non-null    int64
 7   Coverage-Rev    364 non-null    int64
 8   Coverage-Total  364 non-null    int64
 9   TypeB           52 non-null     object
 10  wt              364 non-null    object
 11  mut             364 non-null    object
 12  mylocus         364 non-null    object
dtypes: float64(1), int64(4), object(8)
memory usage: 37.1+ KB
None

Here checks the duplication of positions

<b>Question 1: there're a amount of duplicates, how do we encode them?</b>
    
I've checked with the original file and these duplicate do exist

In [181]:
db[db.Pos.duplicated(keep=False)]

,SampleID,Pos,Ref,Variant,Major/Minor,Variant-Level,Coverage-FWD,Coverage-Rev,Coverage-Total,TypeB,wt,mut,mylocus
73,washei50433.BQSR.recaled.bam,943,T,G,T/G,0.0607,203,1280,1483,NaN,-,-,large-I
74,washei50433.BQSR.recaled.bam,943,T,A,T/A,0.0270,203,1280,1483,NaN,-,-,large-I
108,washei50433.BQSR.recaled.bam,412,C,G,C/G,0.0702,1280,286,1566,yes,-,-,short-I
109,washei50433.BQSR.recaled.bam,412,C,T,C/T,0.0307,1280,286,1566,NaN,-,-,short-I
111,washei50433.BQSR.recaled.bam,410,T,A,T/A,0.0509,1289,282,1571,yes,-,-,short-I
112,washei50433.BQSR.recaled.bam,410,T,G,T/G,0.0197,1289,282,1571,NaN,-,-,short-I
120,washei50433.BQSR.recaled.bam,2505,A,C,A/C,0.2213,1090,1282,2372,NaN,-,-,large-I
121,washei50433.BQSR.recaled.bam,2505,A,T,A/T,0.0160,1090,1282,2372,NaN,-,-,large-I
122,washei50433.BQSR.recaled.bam,2505,A,G,A/G,0.0076,1090,1282,2372,NaN,-,-,large-I
160,washei50433.BQSR.recaled.bam,621,T,C,T/C,0.1805,4571,3118,7689,yes,His,His,Exon421
161,washei50433.BQSR.recaled.bam,621,T,A,T/A,0.0113,4571,3118,7689,NaN,His,Gln,Exon421
166,washei50433.BQSR.recaled.bam,612,G,T,G/T,0.0560,4431,2834,7265,NaN,Glu,Asp,Exon421
167,washei50433.BQSR.recaled.bam,612,G,C,G/C,0.0226,4431,2834,7265,NaN,Glu,Asp,Exon421
177,washei50433.BQSR.recaled.bam,602,G,T,G/T,0.0484,3831,2140,5971,NaN,Gly,Val,Exon421
178,washei50433.BQSR.recaled.bam,602,G,C,G/C,0.0285,3831,2140,5971,NaN,Gly,Ala,Exon421
192,washei50433.BQSR.recaled.bam,675,C,T,C/T,0.0744,4704,4759,9463,NaN,Thr,Thr,Exon421
193,washei50433.BQSR.recaled.bam,675,C,A,C/A,0.0636,4704,4759,9463,NaN,Thr,Thr,Exon421
195,washei50433.BQSR.recaled.bam,672,A,G,A/G,0.1045,4848,4658,9506,NaN,Arg,Arg,Exon421
196,washei50433.BQSR.recaled.bam,672,A,C,A/C,0.0307,4848,4658,9506,NaN,Arg,Ser,Exon421
197,washei50433.BQSR.recaled.bam,666,A,T,A/T,0.0469,5015,4634,9649,yes,Thr,Thr,Exon421
198,washei50433.BQSR.recaled.bam,666,A,C,A/C,0.0216,5015,4634,9649,NaN,Thr,Thr,Exon421
209,washei50433.BQSR.recaled.bam,650,A,T,A/T,0.0874,5154,4151,9305,NaN,Tyr,Phe,Exon421
210,washei50433.BQSR.recaled.bam,650,A,C,A/C,0.0145,5154,4151,9305,NaN,Tyr,Ser,Exon421
228,washei50433.BQSR.recaled.bam,588,T,A,T/A,0.0386,3765,1776,5541,NaN,Thr,Thr,Exon421
229,washei50433.BQSR.recaled.bam,588,T,G,T/G,0.0155,3765,1776,5541,NaN,Thr,Thr,Exon421
232,washei50433.BQSR.recaled.bam,573,C,G,C/G,0.0245,3111,1381,4492,NaN,-,-,near_splice
233,washei50433.BQSR.recaled.bam,573,C,A,C/A,0.0223,3111,1381,4492,NaN,-,-,near_splice
243,washei50433.BQSR.recaled.bam,4806,G,T,G/T,0.0479,2056,1723,3779,NaN,Arg,Met,Exon422
244,washei50433.BQSR.recaled.bam,4806,G,C,G/C,0.0400,2056,1723,3779,NaN,Arg,Thr,Exon422
246,washei50433.BQSR.recaled.bam,4804,G,C,G/C,0.0282,2033,1755,3788,NaN,Thr,Thr,Exon422
247,washei50433.BQSR.recaled.bam,4804,G,A,G/A,0.0190,2033,1755,3788,NaN,Thr,Thr,Exon422
265,washei50433.BQSR.recaled.bam,4876,G,T,G/T,0.0479,1666,2074,3740,NaN,Ala,Ala,Exon422
266,washei50433.BQSR.recaled.bam,4876,G,C,G/C,0.0094,1666,2074,3740,NaN,Ala,Ala,Exon422
268,washei50433.BQSR.recaled.bam,4870,C,G,C/G,0.0591,1643,2166,3809,NaN,Ala,Ala,Exon422
269,washei50433.BQSR.recaled.bam,4870,C,A,C/A,0.0294,1643,2166,3809,NaN,Ala,Ala,Exon422
300,washei50433.BQSR.recaled.bam,4701,G,A,G/A,0.1301,1680,825,2505,NaN,-,-,large-I
301,washei50433.BQSR.recaled.bam,4701,G,T,G/T,0.0088,1680,825,2505,NaN,-,-,large-I
315,washei50433.BQSR.recaled.bam,4740,C,G,C/G,0.0514,2235,1402,3637,NaN,-,-,near_splice
316,washei50433.BQSR.recaled.bam,4740,C,T,C/T,0.0135,2235,1402,3637,NaN,-,-,near_splice
318,washei50433.BQSR.recaled.bam,4755,T,G,T/G,0.0452,2372,1630,4002,NaN,Met,Arg,Exon422
319,washei50433.BQSR.recaled.bam,4755,T,A,T/A,0.0260,2372,1630,4002,NaN,Met,Lys,Exon422
320,washei50433.BQSR.recaled.bam,4755,T,C,T/C,0.0147,2372,1630,4002,NaN,Met,Thr,Exon422
327,washei50433.BQSR.recaled.bam,766,A,C,A/C,0.0432,2410,3868,6278,NaN,-,-,near_splice
328,washei50433.BQSR.recaled.bam,766,A,T,A/T,0.0331,2410,3868,6278,NaN,-,-,near_splice
342,washei50433.BQSR.recaled.bam,727,T,A,T/A,0.1897,3522,4452,7974,NaN,Tyr,Asn,Exon421
343,washei50433.BQSR.recaled.bam,727,T,C,T/C,0.0227,3522,4452,7974,NaN,Tyr,His,Exon421
353,washei50433.BQSR.recaled.bam,707,C,A,C/A,0.1572,3720,4499,8219,NaN,Ser,STOP,Exon421
354,washei50433.BQSR.recaled.bam,707,C,G,C/G,0.0355,3720,4499,8219,NaN,Ser,Trp,Exon421
360,washei50433.BQSR.recaled.bam,781,G,C,G/C,0.1571,1996,3505,5501,NaN,-,-,large-I
361,washei50433.BQSR.recaled.bam,781,G,T,G/T,0.0356,1996,3505,5501,NaN,-,-,large-I

# Features

## id

We no longer need the alphabetical characters -- the number digits carrys all the information we need

In [8]:
def extract_ID(SampleID):
    """
    Helper function clean Sample ID to pure digits
    
    Args:
        SampleID: String, in "washei*****.BQSR.recaled.bam" format, where * stand for numbers
    Return:
        String, the number characters in the middle
    """
    return re.findall(r"[0-9]+", SampleID)[0]

In [186]:
db.SampleID = db.SampleID.apply(extract_ID)
db.head()

,SampleID,Pos,Ref,Variant,Major/Minor,Variant-Level,Coverage-FWD,Coverage-Rev,Coverage-Total,TypeB,wt,mut,mylocus
0,50433,287,C,A,C/A,0.0886,450,69,519,yes,-,-,short-I
1,50433,271,G,C,G/C,0.0835,425,66,491,yes,-,-,short-I
2,50433,1106,G,A,G/A,0.0413,57,452,509,NaN,-,-,large-I
3,50433,1110,C,T,C/T,0.0640,53,431,484,NaN,-,-,large-I
4,50433,1124,C,G,C/G,0.0352,48,406,454,NaN,-,-,large-I

## Ref, Variant, Major/Minor, and Variant-Level

looks like Ref/Variant = Major/Minor? Trying to find odds

In [10]:
db[db.Ref+"/"+db.Variant != db["Major/Minor"]]

,SampleID,Pos,Ref,Variant,Major/Minor,Variant-Level,Coverage-FWD,Coverage-Rev,Coverage-Total,TypeB,wt,mut,mylocus
83,50433,35,C,G,G/C,0.5874,101,42,143,NaN,-,-,short-I
96,50433,4358,A,G,G/A,0.4837,186,29,215,no,-,-,large-I
127,50433,4265,C,T,T/C,0.7297,92,19,111,no,-,-,large-I
165,50433,4576,C,G,G/C,0.9307,993,132,1125,no,-,-,large-I

Alright, what's the threshold?

In [11]:
db[db["Variant-Level"]>0.3]

,SampleID,Pos,Ref,Variant,Major/Minor,Variant-Level,Coverage-FWD,Coverage-Rev,Coverage-Total,TypeB,wt,mut,mylocus
83,50433,35,C,G,G/C,0.5874,101,42,143,NaN,-,-,short-I
96,50433,4358,A,G,G/A,0.4837,186,29,215,no,-,-,large-I
127,50433,4265,C,T,T/C,0.7297,92,19,111,no,-,-,large-I
165,50433,4576,C,G,G/C,0.9307,993,132,1125,no,-,-,large-I
291,50433,859,A,G,A/G,0.3360,590,2306,2896,NaN,-,-,large-I

Looks like the threshold is 0.35+?

## Coverage-FWD,	Coverage-Rev, Coverage-Total

My guess is that Coverage-FWD + Coverage-Rev = Coverage-Total

In [12]:
db[db['Coverage-FWD'] + db['Coverage-Rev'] != db['Coverage-Total'] ]

Empty DataFrame
Columns: [SampleID, Pos, Ref, Variant, Major/Minor, Variant-Level, Coverage-FWD, Coverage-Rev, Coverage-Total, TypeB, wt, mut, mylocus]
Index: []

Thus Coverage-Total doesn't provide much info and provide colinearity in the linear regression, thus I removed them

In [13]:
db = db.drop(['Coverage-Total'], axis = 'columns')

## TypeB

In [14]:
db['TypeB'].value_counts()

yes    49
no      3
Name: TypeB, dtype: int64

## WT

In [15]:
db['wt'].value_counts()

-      230
Thr     19
Ala     18
Arg     14
Gly     13
Ser     12
Tyr     11
Gln     10
Val      9
Pro      7
Glu      6
His      5
Met      4
Ile      2
Cys      1
Asp      1
Asn      1
Leu      1
Name: wt, dtype: int64

In [16]:
db['mut'].value_counts()

-       230
Thr      19
Arg      14
Ser      13
Pro      10
Ala       9
Ile       8
Gln       7
Gly       7
Val       7
Asp       7
Glu       5
His       5
STOP      3
Leu       3
Lys       3
Phe       3
Trp       3
Tyr       3
Cys       2
Asn       2
Met       1
Name: mut, dtype: int64

## mylocus

In [17]:
db['mylocus'].value_counts()

large-I        118
short-I         83
Exon421         76
Exon422         58
near_splice     29
Name: mylocus, dtype: int64

# Summary of loading files

In [18]:
def data_cleaning(df):
    """
    existing data cleaning procedure
    Args:
        df: pandas.DafaFrame instance, the dataframe
    Returns:
        df: pandas.DafaFrame instance, the dataframe with cleaned ID and removed 'Coverage-Total'
    """
    df.SampleID = df.SampleID.apply(extract_ID)
    df.drop(['Coverage-Total'], axis = 'columns', inplace = True)
    return df

In [19]:
def data_cleaning_wrapper(path_list):
    """
    The wrapper for a loading files
    Args:
        path_list: str, the path hold all Coassin pipeline output
    Return:
        df: pandas.DafaFrame instance, all the data should be loaded
    """
    return pd.concat([
        data_cleaning(get_file(file)) 
        for file in path_list
    ], 
        axis = "index", 
        ignore_index = True)

In [390]:
test = ['washei49194.BQSR.recaled.bam',
 'washei62376.BQSR.recaled.bam',
 'washei45948.BQSR.recaled.bam',
 'washei55083.BQSR.recaled.bam',
 'washei50433.BQSR.recaled.bam']

In [391]:
df = data_cleaning_wrapper(test)

In [392]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1806 entries, 0 to 1805
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   SampleID       1806 non-null   object
 1   Pos            1806 non-null   int64
 2   Ref            1806 non-null   object
 3   Variant        1806 non-null   object
 4   Major/Minor    1806 non-null   object
 5   Variant-Level  1806 non-null   float64
 6   Coverage-FWD   1806 non-null   int64
 7   Coverage-Rev   1806 non-null   int64
 8   TypeB          281 non-null    object
 9   wt             1806 non-null   object
 10  mut            1806 non-null   object
 11  mylocus        1806 non-null   object
dtypes: float64(1), int64(3), object(8)
memory usage: 169.4+ KB

# Approach 1: only use the variant itself

Very straightforward thinking method from artificial neural network users

Given a base sequence(as the reference), all of the additional traits are some function $$f(original\_q, new\_q)$$ of the original fastq file and new fastq file. If I'm finding a $$g(original\_q, new\_q, additional\_traits)$$ approximate the distribution of the phenotype, it's equivalent to 
\begin{align}
  &g(original\_q, new\_q, additional\_traits)\\
= &g(original\_q, new\_q, f(original_q, new_q))\\
= &G(original\_q, new\_q)
\end{align}

Thus I only focus on the original position and the variants

In [387]:
def ref_variant_only(df):
    """
    a test function returning the ref_variant informations only
    """
    # change the reference-variant into one column in <reference>/<variant> format
    df["variant"] = df.Ref+"/"+df.Variant
    # only select ID, Position and Variant
    df = df[['SampleID', 'Pos', "variant"]]
    # group by SamplaID and Position
    dg = df.groupby(["SampleID","Pos"])["variant"].apply(list)
    # For each sample id column we have only one value, so expand the table with positions
    dg = pd.DataFrame(dg).stack().unstack(level=1)
    # Reset the index
    dg.reset_index(inplace = True)
    # Drop the information which is irrelavant
    dg.drop("level_1", axis = 1, inplace = True)
    dg.columns.name = None
    dg.set_index("SampleID", inplace = True)
    return dg

In [393]:
dg = ref_variant_only(df)

In [396]:
dg

,21,31,35,50,70,91,105,112,132,141,...,5007,5012,5035,5037,5045,5046,5052,5055,5069,5092
SampleID,,,,,,,,,,,,,,,,,,,,,
45948,[G/A],[T/C],NaN,[C/G],[C/T],[T/C],[C/T],[C/T],[C/T],[A/G],...,[T/C],NaN,[C/A],[T/G],[A/G],[C/T],[A/T],[A/G],[C/T],[G/T]
49194,[G/A],[T/C],[C/G],[C/G],[C/T],[T/C],[C/T],[C/T],[C/T],[A/G],...,[T/C],NaN,[C/A],[T/G],[A/G],[C/T],[A/T],[A/G],[C/T],[G/T]
50433,[G/A],[T/C],[C/G],[C/G],[C/T],[T/C],[C/T],[C/T],[C/T],[A/G],...,[T/C],NaN,[C/A],[T/G],[A/G],[C/T],[A/T],[A/G],[C/T],[G/T]
55083,[G/A],[T/C],NaN,[C/G],[C/T],[T/C],[C/T],[C/T],[C/T],[A/G],...,[T/C],NaN,[C/A],[T/G],[A/G],[C/T],[A/T],[A/G],[C/T],[G/T]
62376,NaN,NaN,[C/G],NaN,[C/T],[T/C],NaN,[C/T],[C/T],[A/G],...,[T/C],[G/A],[C/A],[T/G],[A/G],[C/T],[A/T],[A/G],[C/T],[G/T]

In [403]:
test = dg.iloc[2]

In [405]:
len(test)

458

In [400]:
dg.index

Index(['45948', '49194', '50433', '55083', '62376'], dtype='object', name='SampleID')

In [380]:
def listize(x):
    try:
        if len(x)>1:
            return list(x)
        else:
            return x
    except:
        return x

In [303]:
df_old.set_index(["SampleID",'Pos'], inplace = True)
df_old

              variant
SampleID Pos
49194    4723     G/A
         4721     G/C
         4727     C/T
         4728     G/C
         4734     G/T
...               ...
55083    4843     G/A
         4856     G/A
         4855     C/T
         4862     G/T
         4857     C/A

[1442 rows x 1 columns]

In [309]:
df_old.unstack(level = -1)

ValueError: Index contains duplicate entries, cannot reshape

0     SampleID    49194
      Pos          4723
      variant       G/A
1     SampleID    49194
      Pos          4721
                  ...
1440  Pos          4862
      variant       G/T
1441  SampleID    55083
      Pos          4857
      variant       C/A
Length: 4326, dtype: object

In [246]:
count = df_old

In [249]:
count["variant"][count["variant"]!=1]

SampleID  Pos
45948     412     2
          573     2
          588     2
          602     2
          612     2
                 ..
62376     4740    2
          4755    3
          4804    2
          4806    2
          4870    2
Name: variant, Length: 77, dtype: int64

In [155]:
dg = df.groupby(["SampleID","Pos"])

In [139]:
pd.get_dummies(df)

,21_G/A,31_T/C,35_C/G,37_C/T,50_C/G,70_C/T,91_T/C,105_C/T,112_C/T,113_C/A,...,5055_A/G,5060_G/A,5069_C/T,5078_G/A,5084_C/A,5084_C/G,5084_C/T,5088_C/A,5089_G/A,5092_G/T
SampleID,,,,,,,,,,,,,,,,,,,,,
30519,1,1,1,0,1,1,1,0,1,0,...,1,0,1,0,0,0,0,0,0,1
35552,1,1,1,0,0,0,0,0,0,0,...,1,0,1,0,0,1,0,0,0,1
35789,0,1,0,0,1,1,1,1,1,0,...,1,0,1,0,0,0,0,0,0,1
36424,0,0,1,0,0,0,1,0,1,0,...,1,0,1,0,0,0,0,0,0,1
36523,0,0,1,0,0,1,0,0,0,0,...,1,0,1,0,0,0,0,0,0,1
36578,1,1,0,0,1,1,1,1,1,0,...,1,0,1,0,0,0,0,0,0,1
36745,1,1,1,0,1,0,0,0,0,0,...,1,0,1,0,0,0,0,0,0,1
37104,0,0,0,0,0,0,0,0,0,0,...,1,0,1,0,0,0,0,0,0,1
37161,0,0,1,0,0,0,0,0,0,0,...,1,0,1,0,0,0,0,0,0,1
37200,1,1,0,0,1,0,0,1,1,0,...,1,0,1,0,0,0,0,0,1,1
37244,0,0,0,0,1,1,1,1,1,0,...,1,0,1,0,0,0,0,0,0,1
37405,1,1,1,0,1,1,1,1,1,0,...,1,0,1,0,0,0,0,0,0,1
37581,0,1,1,0,0,1,1,1,1,0,...,1,0,1,0,0,0,0,0,0,1
37802,0,0,1,1,0,0,0,0,1,0,...,1,0,1,0,0,0,0,0,0,1
38292,1,1,1,0,1,0,0,0,0,0,...,1,0,1,0,0,0,0,0,0,1
38672,1,0,1,0,1,1,1,1,1,0,...,1,0,1,0,0,0,0,0,0,1
39488,1,1,1,1,1,1,1,1,1,0,...,1,0,1,0,0,0,1,0,0,1
40926,1,1,1,0,1,1,1,1,1,0,...,1,0,1,0,0,0,0,0,0,1
41386,0,0,0,0,0,0,0,0,0,0,...,1,0,1,0,0,0,0,1,0,1
41462,1,1,1,0,1,1,1,1,1,0,...,1,0,1,0,0,0,0,1,0,1
41780,1,1,1,0,1,1,1,1,1,0,...,1,0,1,0,0,0,0,0,0,1
45233,0,0,1,0,0,1,0,0,0,0,...,1,0,1,0,0,0,0,0,1,1
45936,1,1,0,0,1,1,1,1,1,0,...,1,0,1,0,0,0,0,0,0,1
45953,0,1,1,1,1,1,1,1,1,0,...,1,0,1,0,0,0,0,0,0,1
46024,0,0,1,0,0,1,1,1,1,0,...,1,0,1,1,0,0,0,0,0,1
46947,1,1,0,0,1,1,1,1,1,0,...,1,0,1,0,0,0,0,0,0,1
47561,1,1,0,0,1,1,1,1,1,0,...,1,0,1,0,0,0,0,0,0,1
47600,0,0,1,0,1,1,1,1,1,0,...,1,0,1,0,0,0,0,0,0,1
48272,1,1,0,0,1,1,1,1,1,0,...,1,0,1,0,0,0,0,0,0,1
48294,0,1,1,0,0,0,0,0,1,0,...,1,1,1,0,0,0,0,0,0,1
48310,1,1,0,0,1,1,1,1,1,0,...,1,0,1,0,0,0,0,0,0,1
48375,1,1,1,0,1,1,1,1,1,0,...,1,0,1,0,0,0,0,0,0,1
48393,1,1,1,0,1,0,1,0,1,0,...,0,0,0,0,1,0,0,0,0,1
48412,1,1,1,0,1,1,1,1,1,0,...,1,0,1,0,0,0,0,0,0,1
49132,1,1,1,0,0,0,1,0,0,1,...,1,0,1,0,0,0,0,0,0,1
49253,1,1,1,0,1,1,1,1,1,0,...,1,0,1,0,0,0,0,0,0,0
50433,1,1,1,0,1,1,1,1,1,0,...,1,0,1,0,0,0,0,0,0,1
50468,1,1,1,0,1,1,0,0,0,0,...,1,0,0,0,0,0,0,1,0,0
50956,1,1,0,0,1,1,1,1,1,0,...,1,0,1,0,0,0,0,0,0,1
52000,0,0,1,0,0,1,1,1,1,0,...,1,0,0,0,0,0,0,0,0,1
54981,0,0,0,0,0,0,1,1,1,0,...,1,0,1,0,0,0,0,0,0,1
55025,0,0,1,0,0,0,0,0,0,0,...,1,0,1,0,0,0,0,0,0,1
55040,1,1,1,0,1,1,1,1,1,1,...,1,0,1,0,0,1,0,0,0,1
57592,1,1,1,0,1,1,1,1,1,0,...,1,1,1,0,0,0,0,0,0,1
57615,1,1,1,0,1,1,1,1,1,0,...,1,0,1,0,0,0,0,0,0,1
57791,0,0,1,0,1,1,0,0,0,0,...,1,0,1,0,0,0,0,0,0,1
62254,0,1,1,0,0,0,0,0,1,0,...,1,0,1,0,0,0,0,0,0,1
62451,1,1,1,0,0,0,1,1,1,0,...,1,0,1,0,1,0,0,0,0,0
62533,0,0,1,0,0,0,0,0,0,0,...,1,0,1,0,1,0,0,0,0,1
69617,1,1,0,0,1,1,1,0,0,0,...,1,0,1,0,0,0,0,1,0,1